name: Release

on:
  push:
    tags:
      - '**'

jobs:
  release:
    runs-on: ubuntu-latest
      CF_API_KEY:${{ secrets.CF_API_KEY }}
      WAGO_API_TOKEN:${{ secrets.WAGO_API_TOKEN }}
      GITHUB_OAUTH:${{ secrets.GITHUB_TOKEN }}
      
      - name:Clone project
        uses:actions/checkout@v3
        with:fetch-depth:0

      - name:Release
        uses:BigWigsMods/packager@v2
