name: Release

on:
  push:
    branches:
      - master
    tags:
      - '**'
    paths-ignore:
      - 'assets'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: WoW Packager
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}